INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, 'Quatro Vidas de Um Cachorro', 'https://www.themoviedb.org/t/p/w220_and_h330_face/3W5jF8z5GkOHEslaIv89Ncp06J4.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3, 'Marley & Eu', 'https://www.themoviedb.org/t/p/original/5pcKISTj5HcymadKuSeK2hql2Bg.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Sempre ao Seu Lado', 'https://i.imgur.com/wiGGC3y.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Juntos Para Sempre', 'https://i.imgur.com/wbhIxKJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Togo', 'https://i.imgur.com/y4BjC6z.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Beethoven, O Magnífico', 'https://i.imgur.com/l2SDpii.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Dama e o Vagabundo', 'https://i.imgur.com/1fbMpbS.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, '102 Dálmatas', 'https://i.imgur.com/dCyBDxd.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Max', 'https://i.imgur.com/KebSEQH.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Querido Companheiro', 'https://i.imgur.com/rqvi1iw.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Um Hotel Bom pra Cachorro', 'https://i.imgur.com/bITtwQv.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Aucademia', 'https://i.imgur.com/J1be5DN.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Patrulha Canina', 'https://i.imgur.com/fq0AaAI.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Pretzel e os Filhotes', 'https://i.imgur.com/PaOsdz1.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Procura-se um Amor que Goste de Cachorros', 'https://i.imgur.com/wpqzJHt.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Soltando os Cachorros', 'https://i.imgur.com/8NZ0NF8.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Palácio para cachorros', 'https://i.imgur.com/Jjm8jQl.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Casa é dos Cachorros', 'https://i.imgur.com/Ass72ti.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Ilha dos Cachorros', 'https://i.imgur.com/N360l8o.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Space Buddies: Uma Aventura no Espaço', 'https://i.imgur.com/E75IWWG.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Bud 3: Jogando Futebol', 'https://www.themoviedb.org/t/p/w220_and_h330_face/bYtxJ7Dq3zzKB14ZKWpAGtCqcsC.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homens e Cachorros: Um Amor pra Vida Toda', 'https://www.themoviedb.org/t/p/w220_and_h330_face/cPhr5ZjtqcFiG2yAvpC4F9yIR9W.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Os Filhotes da Mamãe Noel', 'https://www.themoviedb.org/t/p/w220_and_h330_face/x07UZ6nvbuFQEY8hyUxsCI1gCoX.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Spooky Buddies: A Casa Mal-Assombrada', 'https://www.themoviedb.org/t/p/w220_and_h330_face/7vTF5sxsUGPaKvuQki1WU0pE2OQ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Marley & Eu 2 - Filhote Encrenqueiro', 'https://www.themoviedb.org/t/p/w220_and_h330_face/x10cgSz3ePjbls4Eyufu9ySopvQ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Benji - Um Cão Desafia a Selva', 'https://www.themoviedb.org/t/p/w220_and_h330_face/4ix6fvEvRzW2Fw4QJMypVEnMnHh.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Snow Buddies: Uma Aventura no Gelo', 'https://www.themoviedb.org/t/p/w220_and_h330_face/1BCIWKuyHx7xCHr3C2JFT7EfIP7.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Uma Aventura Animal', 'https://www.themoviedb.org/t/p/w220_and_h330_face/d1OA5OHJsY6wCHKuOmICwyl8Byy.jpg');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);
